CREATE TABLE IF NOT EXISTS worker(
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(1000) NOT NULL,
  BIRTHDAY DATE,
  LEVEL VARCHAR(50)NOT NULL,
  SALARY int,
  CONSTRAINT CHK_worker CHECK (SALARY>=100 AND SALARY<=100000)
  );

ALTER TABLE worker ADD CONSTRAINT LEVEL_ENUM_VALUES CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior'));

CREATE TABLE IF NOT EXISTS clientID(
ID IDENTITY PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS client(
  Client_ID INTEGER NOT NULL ,
  NAME_ID INTEGER NOT NULL,
  FOREIGN KEY (Client_ID) REFERENCES clientID(ID),
  FOREIGN KEY (NAME_ID) REFERENCES WORKER(ID),
  primary key(Client_ID, NAME_ID)
);


CREATE TABLE IF NOT EXISTS project (
  ID IDENTITY PRIMARY KEY,
  CLIENT_ID BIGINT NOT NULL,
  START_DATE DATE,
  FINISH_DATE DATE
  );

CREATE TABLE IF NOT EXISTS PROJECT_WORKER(
    PROJECT_ID BIGINT NOT NULL,
    WORKER_ID  BIGINT NOT NULL,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (WORKER_ID) REFERENCES WORKER (ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
);